# Generated by Django 4.2.7 on 2025-12-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team_a_name", models.CharField(max_length=100)),
                ("team_a_code", models.CharField(max_length=3)),
                ("team_b_name", models.CharField(max_length=100)),
                ("team_b_code", models.CharField(max_length=3)),
                (
                    "start_time",
                    models.DateTimeField(help_text="Match start time in UTC"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("venue", models.CharField(max_length=200)),
                (
                    "tournament_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tournament_year", models.IntegerField(blank=True, null=True)),
                ("group", models.CharField(blank=True, max_length=20, null=True)),
                ("score_a", models.IntegerField(blank=True, null=True)),
                ("score_b", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Admin override for prediction locking"
                    ),
                ),
                (
                    "lock_override_time",
                    models.DateTimeField(
                        blank=True, help_text="Custom lock time override", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=3, unique=True)),
                ("flag", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "name"],
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="matches.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("tournament", "name")},
            },
        ),
    ]
