# Generated by Django 4.2.7 on 2025-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="extra_time",
            field=models.IntegerField(
                default=0, help_text="Extra/stoppage time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="final_whistle_time",
            field=models.DateTimeField(
                blank=True, help_text="Time when match actually ended", null=True
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("live", "Live"),
                    ("extra_time", "Extra Time"),
                    ("finished", "Finished"),
                    ("postponed", "Postponed"),
                    ("cancelled", "Cancelled"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
