# Generated by Django 4.2.7 on 2026-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_match_extra_time_match_final_whistle_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("live", "Live"),
                    ("extra_time", "Extra Time"),
                    ("finished", "Finished"),
                    ("completed", "Completed"),
                    ("postponed", "Postponed"),
                    ("cancelled", "Cancelled"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
