# Generated by Django 4.2.7 on 2025-12-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_phone_user_unique_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("phone",),
                name="unique_phone",
            ),
        ),
    ]
