# Generated by Django 4.2.7 on 2025-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_unique_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notified",
            field=models.BooleanField(
                default=False,
                help_text="Whether admin has been notified about this user",
            ),
        ),
    ]
