# Generated by Django 4.2.7 on 2026-01-08 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
