# Generated by Django 4.2.7 on 2026-01-12 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_passwordresettoken_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
