# Generated by Django 4.2.7 on 2026-01-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_delete_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
