# Generated by Django 4.2.7 on 2026-01-14 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_avatar_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
