# Generated by Django 4.2.7 on 2026-01-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
