apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: predication_2026-frontend:latest
          imagePullPolicy: IfNotPresent
          args: ["npm", "start"]
          env:
            - name: REACT_APP_API_URL
              value: http://localhost:8000
            - name: REACT_APP_BACKEND_URL
              value: http://localhost:8000
            - name: REACT_APP_FOOTBALL_API_URL
              value: https://media.api-sports.io/
            - name: REACT_APP_FOOTBALL_API_KEY
              value: c27d5af3460e0b3e90fdd80dcef3fa02
            - name: REACT_APP_DEBUG
              value: "true"
            - name: REACT_APP_ENVIRONMENT
              value: development
            - name: WDS_SOCKET_PORT
              value: "0"
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
